### ISSUE TITLE
webpack missing angular-ui-router

### ISSUE THREAD

**Issue by hanscoder** [goosefraba/ng-starterkit#1]
After cloning the repository and change to branch alpha I started gulp ui:build (ui:compile) and get following stacktrace:
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
ModuleNotFoundError: Module not found: Error: Cannot resolve module 'angular-ui-router' in C:\Data\dev\projects\ng-starterkit\src\app
    at C:\Data\dev\projects\ng-starterkit\node_modules\webpack\lib\Compilation.js:229:38
    at onDoneResolving (C:\Data\dev\projects\ng-starterkit\node_modules\webpack\lib\NormalModuleFactory.js:29:20)
    at C:\Data\dev\projects\ng-starterkit\node_modules\webpack\lib\NormalModuleFactory.js:85:20
    at C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\async\lib\async.js:721:13
    at C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at done (C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\async\lib\async.js:241:17)
    at C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\async\lib\async.js:44:16
    at C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\async\lib\async.js:718:17
    at C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\async\lib\async.js:167:37
    at C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:24:19
    at onResolved (C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:38:18)
    at innerCallback (C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:94:11)
    at loggingCallbackWrapper (C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:21:19)
    at C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\tapable\lib\Tapable.js:134:6
    at C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\enhanced-resolve\lib\ModulesInDirectoriesPlugin.js:54:23
    at C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:191:15
    at C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\enhanced-resolve\lib\ModulesInDirectoriesPlugin.js:45:26
    at loggingCallbackWrapper (C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:21:19)
    at C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\tapable\lib\Tapable.js:134:6
    at C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:122:33
    at C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (C:\Data\dev\projects\ng-starterkit\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:110:4)

**Comment by mrmuh** [comment]
hi! 
after checkout have you done npm install and bower install? Have you noticed problems during installation? I tried to reproduce it on windows (node 0.10.35) and ubuntu (node 4.2.1) but I cannot reproduce the problem. From the stackstrace it looks like the installation of the bower dependencies failed somehow. Could you please check if the bower dependencies are properly installed (angular-ui-router etc.)?

**Comment by hanscoder** [comment]
Hi
It seems there is a problem with a proxy or npm install and bower isntall didn't work correctly. I tried it in an other environment and it workw correctly. Actually we can close the issue.

Thanks for your answer.
